### ISSUE TITLE
create-distance is broken

### ISSUE THREAD

**Issue by pintoso** [FunnyGuilds/FunnyGuilds#1331]
can someone explain to me how `create-distance` works?
because the way it is working now is problematic

1. spawn is `0, 0`
2. I set `create-distance: 1000` +100 distance (plugin adds by itself, this is not a problem btw)
3. so players have to move away **1100 blocks**
4. if I go to `0, 1100` I can create a guild, ok perfect
5. but if I go in any diagonal direction, I can make guilds before reaching 1100
(look at the image, I created a guild in 767, 791)
![image](https://user-images.githubusercontent.com/26844778/93719882-df968200-fb5b-11ea-9ca4-35976788e8ff.png)

I think that the way used to calculate the distance must be changed, because apparently the "safe area" created is a circle(?).
This causes problems when trying to keep a large area safe and there is no option to set a square instead of a circle.

FG VERSION: `4.7.0 Tribute-77aeb72`
PAPER 1.16.1

> >is a big problem in my vision, but I can get around blocking commands in the worldguard region

I recommend adding a new option "square" (or whatever you want)

for example:
```
create-distance: 1000
create-distance-type: square
```

this type of distance is the same value in all directions
if someone didn't understand and need a reference 
use the following commands with worldedit in the same block
`//pos1` **>** `//pos2` **>** `//outset 10` **>** `//expand vert`
![image](https://user-images.githubusercontent.com/26844778/93720084-289b0600-fb5d-11ea-9be5-64216014bd7c.png)

> >I think everyone here understands what I say, but it costs me nothing to explain

> > >a worldguard flag to block the creation of guilds in a region will be very useful and a quick solution

**Comment by insertt** [comment]
Currently our implementation calculates the distance between two points in a 3D space, so that's why you can create a guild with configured minimum distance of 1000 on coordinates like (767, 791) and I agree that this behavior could be non-intuitive for some people, so we probably should consider adding option `create-distance-type` just like you mentioned. 

Also, in your example the resulting minimum distance was `1100`, because we're including the guild region size in the final minimum distance, so that you don't have to change a minimum distance from the spawn when you've changed a guild region size option.
