### ISSUE TITLE
warny mysql baza danych

### ISSUE THREAD

**Issue by wcplmr** [FunnyGuilds/FunnyGuilds#1858]
załączam logi i config w załączniku config zmieniłem format na txt bo w yml nie mogę wysłać 
[latest.log](https://github.com/FunnyGuilds/FunnyGuilds/files/8216658/latest.log)
 
[config.txt](https://github.com/FunnyGuilds/FunnyGuilds/files/8216666/config.txt)

**Comment by Kamilkime** [comment]
To raczej wygląda na jakieś problemy z samą bazą MySQL, a nie z FunnyGuilds. Ewentualnie możesz zmienić `poolSize` w configu na jakiś stały, a nie dawać tam -1 - może np. twoja baza nie przyjmuje tyle połączeń ile FG próbuje rezerwować.

A poza tym - najlepiej pobierz sobie też najnowszą [wersję nightly](https://ci.insertt.dev/job/FunnyGuilds/job/master/), wersja 4.9.7 jest już dość stara (tylko zrób dla pewności kopię danych wszystkich przed zmianą jara pluginu).

**Comment by wcplmr** [comment]
zmieniłem wersje nadal ten sam błąd według hostingu moja baza danych ma limit do 300 połączeń

**Comment by Kamilkime** [comment]
No to już jest problem z bazą lub ogólnie z połączeniami od twojego serwera. Tu jest całkiem niezły opis czemu tak się może dziać: https://tableplus.com/blog/2019/08/host-is-blocked-because-of-many-connection-errors.html.

Przede wszystkim upewnij się, że we wszystkich pluginach podajesz prawidłowe dane do MySQL.
